### ISSUE TITLE
JWT token should be created via the configured TOKEN_OBTAIN_SERIALIZER in simplejwt when possible

### ISSUE THREAD

**Issue by jorgelf** [lgoodridge/django-uniauth#10]
Hello,

The current _JWT_ token creation process makes it pretty difficult to add custom claims to them, as it's created manually by calling `RefreshToken.for_user(user)` in method `tokens.get_jwt_tokens_for_user`. It's true this is the way to manually create a token detailed in the _simplejwt_ docs, but a more solid way would be to first check for a configured _TokenObtainPairSerializer_ via the configurable _simplejwt_ parameter _TOKEN_OBTAIN_SERIALIZER_, so we can set up a custom one that adds custom claims to the tokens. I think it could be easily implemented with just a few lines of code:

```python
from django.contrib.auth.tokens import PasswordResetTokenGenerator
from django.utils.module_loading import import_string
from rest_framework_simplejwt.tokens import RefreshToken
from rest_framework_simplejwt.settings import api_settings as jwt_settings


class EmailVerificationTokenGenerator(PasswordResetTokenGenerator):
    """
    Creates tokens for linked email verification.
    """

    def _make_hash_value(self, email, timestamp):
        return str(email.pk) + str(email.is_verified) + str(timestamp)


token_generator = EmailVerificationTokenGenerator()


def get_jwt_tokens_for_user(user, **kwargs):
    """
    Generates a refresh token for the valid user
    """
    try:
        refresh = import_string(jwt_settings.TOKEN_OBTAIN_SERIALIZER).get_token(user)
    except:
        refresh = RefreshToken.for_user(user)

    return str(refresh), str(refresh.access_token)

```

Or maybe there's another way to easily add custom claims in the _JWT_ tokens created with this library, but I haven't been able to find one...

Thanks for the library in any case, very useful. This is just the one real annoyance I've found so far.

**Comment by lgoodridge** [comment]
Appreciate the suggestion again, thanks!

Have to admit, I was flying a little blind since I haven't used custom token serializers with Simple JWT yet, but I poked around the docs and I think the change is good. Fixed in version 1.4.0
