### ISSUE TITLE
InstitutionAccount should have a unique restriction on institution + CAS id

### ISSUE THREAD

**Issue by jorgelf** [lgoodridge/django-uniauth#11]
Right now it's possible to define multiple institution accounts for the same _CAS_ server with the same id, which results in a `MultipleObjectsReturned` exception when trying to log in with that _CAS_ id. A unique restriction on field combination institution + _CAS_ id in `InstitutionAccount` should fix it.

**Comment by lgoodridge** [comment]
Great suggestion! Fixed in version [1.3.2](https://github.com/lgoodridge/django-uniauth/commit/2ed597a2bb60a5f3ee8754c3a62cc8d4d3cfd53e)
