### ISSUE TITLE
uni-auth in other languages

### ISSUE THREAD

**Issue by samuelcalegari** [lgoodridge/django-uniauth#12]
Hello,
It 's possible to translate all texts (front end) in an another language ?
thank u so much

**Comment by lgoodridge** [comment]
Hello,

I'm not currently planning on adding translations in-package unfortunately. If you need this functionality, you can [override the templates](https://github.com/lgoodridge/django-uniauth#template-customization), then translate the text with the rest of the project using [Django's built-in tools](https://docs.djangoproject.com/en/4.2/topics/i18n/translation/).
