### ISSUE TITLE
Method to flush all user accounts created >24hrs that have not been validated

### ISSUE THREAD

**Issue by jlumbroso** [lgoodridge/django-uniauth#7]
This would make it easier to clean up after a spam attack. @andyguna

**Comment by lgoodridge** [comment]
Added in version 1.2.5. You can either use `uniauth.utils.flush_old_tmp_users`, or the `flush_tmp_users` django command (e.g. `python manage.py flush_tmp_users`).

Both accept an optional days argument specifying how old temporary users have to be get deleted, but the default for both is 1.
